[package]
name = "journald-format"
version = "0.1.0"
edition = "2021"

description = "Read and write the journald binary disk format"

[dependencies]
deku = "0.18.1"
siphasher = "1.0.1"
uuid = { version = "1.10.0", features = ["v4"] }
