[package]
name = "journald-format"
version = "0.1.0"
edition = "2021"

description = "Read and write the journald binary disk format"

[dependencies]
bstr = "1.10.0"
deku = "0.18.1"
futures-io = "0.3.30"
siphasher = "1.0.1"
uuid = { version = "1.10.0", features = ["v4"] }
